### ISSUE TITLE
Use with Deconz Conbee

### ISSUE THREAD

**Issue by feldskov** [bulldog5046/Enecsys-Zigbee-HA#2]
Hi

I really like your project! I have Enecsys inverters and a gateway. I would however like to record the data from the inverters directly without the hardware gateway. 

I have tried setting up your virtual gateway - but without success unfortunately. 

I don't have the same Zigbee dongle (and the Sonoff model P is hard to get theese days).

I have a Conbee, that I was hoping to use, but I don't think I am setting up the network properly.

I have tried configuring the network settings via deconz to match the things you have written, but when I enable the virtual gateway home assistant addon, no messages are received from the inverters. It sets up the network, but after joining is permitted, nothing happens.

Have you by any chance any ideas what I could do?

![image](https://user-images.githubusercontent.com/15104714/229375213-16fda401-7300-4ed4-8b39-254eba5e9c43.png)

**Comment by bulldog5046** [comment]
Difficult to say for sure without being able to sniff the traffic separately and see what's going on.

I suspect in the screenshot the TC link Key is actually supplemental and not the built-in default (0x5A6967426565416C6C69616E63653039 (ZigBeeAlliance09)). The inverters send out probe requests that coordinators respond to. If the parameters don't match what they are looking for they stay silent.

You would need to know if the conbee firmware has the above hardcoded key in the firmware as required by the zigbee alliance spec.

Could be easier to just track down a Sonoff dongle. I recently bought another from eBay so wasn't under the impression they are becoming scarce.

**Comment by feldskov** [comment]
Thank you for your quick reply. You are right regarding the TC link key. It has the standard zigbee alliance key by default. It seems to work with changing it via deconz in the “session”, but when device is reset it defaults back. 

I will try to find the Sonoff P dongle on EBay. In Denmark it is out of stock and replaced with the E-version. 

When I find one, I just need to flash it and the it should work, right? :)

Thanks, Jens

**Comment by bulldog5046** [comment]
More or less, You will need to use Zigpy to adjust the PAN ID and Stack Profile. See here for how to do that;

https://github.com/bulldog5046/Enecsys-Zigbee-HA/issues/1#issuecomment-1469835258

Alternatively, you could look to compile your own firmware for the E model dongle. Looks like it uses EmberZNet (EZSP).

**Comment by feldskov** [comment]
Thanks :)
